/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ttgHbB2M2MvGS434ZBzqAV
// Component: pZJT9QJ-6-HP

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Navbar from "../../Navbar"; // plasmic-import: TzYooJ-ChIAu/component
import Button from "../../Button"; // plasmic-import: WVaSXXNCFaQt/component
import Section from "../../Section"; // plasmic-import: rEAlJ2tapI6z/component
import Teams from "../../Teams"; // plasmic-import: nD6DZUA_4wjs/component
import TextInput from "../../TextInput"; // plasmic-import: RYnCW_PWn357/component
import FooterSection from "../../FooterSection"; // plasmic-import: VwP4GkeGOFgi/component

import { useScreenVariants as useScreenVariantsd25QuUa2NRj1 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: d25QUUa2NRj1/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import plasmic_library_tailwind_3_4_colors_css from "../library_tailwind_3_4_color_tokens/plasmic.module.css"; // plasmic-import: 5ZtnypMovRHeeP3YTdPCYL/projectcss
import plasmic_library_tailwind_3_4_number_tokens_css from "../library_tailwind_3_4_number_tokens/plasmic.module.css"; // plasmic-import: 4vjRXvnb4XuY6J15w9oRcQ/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: ttgHbB2M2MvGS434ZBzqAV/projectcss
import sty from "./PlasmicHomepage2.module.css"; // plasmic-import: pZJT9QJ-6-HP/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: wMRgeyBkm7Xv/icon
import ChevronRightIcon from "./icons/PlasmicIcon__ChevronRight"; // plasmic-import: llyQutGx_nWs/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: RTEemw70ViIf/icon
import SearchSvg2Icon from "./icons/PlasmicIcon__SearchSvg2"; // plasmic-import: WHubRTeidzpC/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: wgkKccDR8Lnd/icon

createPlasmicElementProxy;

export type PlasmicHomepage2__VariantMembers = {};
export type PlasmicHomepage2__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage2__VariantsArgs;
export const PlasmicHomepage2__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage2__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage2__ArgsType;
export const PlasmicHomepage2__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage2__OverridesType = {
  root?: Flex__<"div">;
  headerHeroSection?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  svg?: Flex__<"svg">;
  textInput?: Flex__<typeof TextInput>;
  footerSection?: Flex__<typeof FooterSection>;
};

export interface DefaultHomepage2Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage2__RenderFunc(props: {
  variants: PlasmicHomepage2__VariantsArgs;
  args: PlasmicHomepage2__ArgsType;
  overrides: PlasmicHomepage2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsd25QuUa2NRj1()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicHomepage2.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicHomepage2.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicHomepage2.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            plasmic_library_tailwind_3_4_colors_css.plasmic_tokens,
            plasmic_library_tailwind_3_4_number_tokens_css.plasmic_tokens,
            sty.root
          )}
        >
          <Stack__
            as={"div"}
            data-plasmic-name={"headerHeroSection"}
            data-plasmic-override={overrides.headerHeroSection}
            hasGap={true}
            className={classNames(projectcss.all, sty.headerHeroSection)}
          >
            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__vjd3S)}>
              <div className={classNames(projectcss.all, sty.freeBox__uHbf)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__zl6K0
                  )}
                >
                  {"Koblich Chronicles"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vRhm
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
                  }
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__crRzk)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__o7L9)}
                    end={
                      <ChevronRightIcon
                        data-plasmic-name={"svg"}
                        data-plasmic-override={overrides.svg}
                        className={classNames(projectcss.all, sty.svg)}
                        role={"img"}
                      />
                    }
                    iconEnd={true}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wZ3Qf
                        )}
                      >
                        {"View Charts"}
                      </div>
                    }
                    linkTo={"#"}
                    size={"extraLarge"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___37Tp)}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___2Molk
                        )}
                      >
                        {"Check my stats"}
                      </div>
                    }
                    linkTo={"#"}
                    size={"extraLarge"}
                    type={"bordered"}
                  />
                </Stack__>
              </div>
            </div>
          </Stack__>
          <Section
            className={classNames("__wab_instance", sty.section___9VQo)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : "fullContentWidth"
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__yN3D)}>
              <div className={classNames(projectcss.all, sty.columns__j8Vu9)}>
                <div className={classNames(projectcss.all, sty.column__qeaQw)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__teyOo)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"500px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "284px"
                        : "auto"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/image2Png.png",
                      fullWidth: 1040,
                      fullHeight: 1040,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__mm4Uk)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qRzQn)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__hgq9N)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/light_saa_s_landing_page/images/bankSvg.svg",
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3NjNl
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
                        }
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column___2Dz87)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__iwNkr)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kszKc)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__jhrEv)}
                        displayHeight={"2px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"26px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/light_saa_s_landing_page/images/lineBlueSvg.svg",
                          fullWidth: 300,
                          fullHeight: 23,
                          aspectRatio: 13
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__diEhD
                        )}
                      >
                        {"Lorem Ipsum"}
                      </div>
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__mk47L
                      )}
                    >
                      {"Lorem Ipsum"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ctNgR
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. "
                      }
                    </div>
                    <Button
                      className={classNames("__wab_instance", sty.button__zda3)}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wHAjR
                          )}
                        >
                          {"lorem Ipsum"}
                        </div>
                      }
                      linkTo={"#"}
                      size={"large"}
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__rin5I)}>
              <div className={classNames(projectcss.all, sty.columns__wmeJn)}>
                <div className={classNames(projectcss.all, sty.column__e9Oe)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qdlPp)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mpOwA)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__hKlXa)}
                        displayHeight={"2px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"26px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/light_saa_s_landing_page/images/lineBlueSvg.svg",
                          fullWidth: 300,
                          fullHeight: 23,
                          aspectRatio: 13
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__npEp
                        )}
                      >
                        {"Lorem Ipsum"}
                      </div>
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__rtKb
                      )}
                    >
                      {"Lorem Ipsum"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ws3GV
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. "
                      }
                    </div>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__phb6P
                      )}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yaLM
                          )}
                        >
                          {"lorem Ipsum"}
                        </div>
                      }
                      linkTo={"#"}
                      size={"large"}
                    />
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__ujHli)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___9OQv0)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "284px"
                        : "500px"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "284px"
                        : "auto"
                    }
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/image3Png.png",
                      fullWidth: 1040,
                      fullHeight: 1040,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__u6E7Y)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wtsR3)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__qItPu)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/light_saa_s_landing_page/images/bankSvg.svg",
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lzrjn
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
                        }
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__qP0Ce)}>
              <div className={classNames(projectcss.all, sty.columns__gNfCx)}>
                <div className={classNames(projectcss.all, sty.column__wfExm)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__u5NKp)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "284px"
                        : "500px"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/image4Png.png",
                      fullWidth: 1040,
                      fullHeight: 1040,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__j7QT)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__wbfEg)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__aB4Vx)}
                        displayHeight={"24px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"24px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/light_saa_s_landing_page/images/bankSvg.svg",
                          fullWidth: 150,
                          fullHeight: 150,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dipY
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
                        }
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.column__xy8J)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__p5Wwi)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ySuz)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__sSuwr)}
                        displayHeight={"2px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"26px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/light_saa_s_landing_page/images/lineBlueSvg.svg",
                          fullWidth: 300,
                          fullHeight: 23,
                          aspectRatio: 13
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ey5Qb
                        )}
                      >
                        {"Lorem Ipsum"}
                      </div>
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___7OA7K
                      )}
                    >
                      {"Lorem Ipsum"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__j9Smo
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. "
                      }
                    </div>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___1HqQh
                      )}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__t1X8
                          )}
                        >
                          {"lorem Ipsum"}
                        </div>
                      }
                      linkTo={"#"}
                      size={"large"}
                    />
                  </div>
                </div>
              </div>
            </div>
          </Section>
          <Section
            background={"darkBlue"}
            className={classNames("__wab_instance", sty.section__w8H2S)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : "fullContentWidth"
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__jzbls)}>
              <div className={classNames(projectcss.all, sty.freeBox__rCbOt)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__eIlj
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Lorem Ipsum"
                    : "Lorem Ipsum"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__berAs
                  )}
                >
                  {hasVariant(globalVariants, "screen", "mobile")
                    ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                    : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."}
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___7Lzb2)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__l1EyE)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__n2NOf)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobile")
                          ? "24px"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/tickCircleSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__dQb7Q)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__efQks
                      )}
                    >
                      {"Lorem ipsum dolor sit amet"}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__ssJtX)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ecWjW)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__sGsdu)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobile")
                          ? "24px"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/tickCircleSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gb2P)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__juPNw
                      )}
                    >
                      {"Lorem ipsum dolor sit amet"}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__vdGnU)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__efmNx)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__vVzlx)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobile")
                          ? "24px"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/tickCircleSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hb6Rx)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e9DBk
                      )}
                    >
                      {"Lorem ipsum dolor sit amet"}
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__e5Zx)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__oJb9D)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__vcPb1)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={
                        hasVariant(globalVariants, "screen", "mobile")
                          ? "24px"
                          : "100%"
                      }
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/tickCircleSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__j8J6R)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0KWvl
                      )}
                    >
                      {"Lorem ipsum dolor sit amet"}
                    </div>
                  </div>
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__zf2Eo)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___1M5Wv)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "100%"
                      : "700px"
                  }
                  displayMaxHeight={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "174px"
                      : "none"
                  }
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "284px"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobile")
                      ? "100%"
                      : "1440px"
                  }
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/light_saa_s_landing_page/images/frame10Png.png",
                    fullWidth: 1070,
                    fullHeight: 1402,
                    aspectRatio: undefined
                  }}
                />

                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__b0XK2)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/light_saa_s_landing_page/images/heroImgPng.png",
                    fullWidth: 2280,
                    fullHeight: 1400,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </Section>
          <Section
            className={classNames("__wab_instance", sty.section__nvd7K)}
            size={"fullContentWidth"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__z15GT)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__okrXn
                )}
              >
                {"Lorem Ipsum"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__aoh2L
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                  : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."}
              </div>
              <Button
                className={classNames("__wab_instance", sty.button__u5Vbv)}
                label={
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aCs0W
                    )}
                  >
                    {"lorem Ipsum"}
                  </div>
                }
                linkTo={"#"}
                size={"extraLarge"}
              />

              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__dA17T)}
              >
                <Teams
                  className={classNames("__wab_instance", sty.teams__oaTb)}
                />

                <Teams
                  className={classNames("__wab_instance", sty.teams__t7TL)}
                />

                <Teams
                  className={classNames("__wab_instance", sty.teams__ae35J)}
                />

                <Teams
                  className={classNames("__wab_instance", sty.teams___7NjNo)}
                />

                <Teams
                  className={classNames("__wab_instance", sty.teams__wMoWi)}
                />

                <Teams
                  className={classNames("__wab_instance", sty.teams__r2Ho4)}
                />
              </Stack__>
            </div>
          </Section>
          <Section
            background={"blue"}
            className={classNames("__wab_instance", sty.section__bVQhj)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : "fullContentWidth"
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox___110Au)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__bkXLq
                )}
              >
                {"Lorem Ipsum"}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__jNe0N
                )}
              >
                {hasVariant(globalVariants, "screen", "mobile")
                  ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                  : "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."}
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__mAd9R)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__boeT3)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__fj3L8)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "114px"
                        : "141px"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/freeForeverSvg.svg",
                      fullWidth: 148,
                      fullHeight: 150,
                      aspectRatio: 0.986014
                    }}
                  />

                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__dgBrt
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Starter"
                      : "Starter"}
                  </h4>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jg9Jw
                    )}
                  >
                    {"Lorem ipsum dolor sit amet, consectetur adipiscing elit"}
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__n9PHo)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"238px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/lineSvg.svg",
                      fullWidth: 300,
                      fullHeight: 3,
                      aspectRatio: 119
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox___12F1N)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__ot0Tk
                      )}
                    >
                      {"$0"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0Y1Vl
                      )}
                    >
                      {"/ Month"}
                    </div>
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__pS7W)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"238px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/lineSvg.svg",
                      fullWidth: 300,
                      fullHeight: 3,
                      aspectRatio: 119
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gcSqu
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Feature"
                      : "Feature"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ntne1)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__dYffG)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gt5I
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__p4CdK)}
                          displayHeight={"20px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"20px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBlueSvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__idaxm
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__suUjh
                          )}
                        >
                          {"Unlimited issue"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__qNs4Y)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__euZt
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__h9JlS)}
                          displayHeight={"20px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"20px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBlueSvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bgl9Y
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dublR
                          )}
                        >
                          {"Free domain"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__evEfn)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rl9Iw
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__dr5S)}
                          displayHeight={"20px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"20px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBlueSvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dBeum
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kJyCz
                          )}
                        >
                          {"3 team accounts"}
                        </div>
                      </div>
                    </div>
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__mthPz)}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wtKiJ
                        )}
                      >
                        {"Get Started"}
                      </div>
                    }
                    linkTo={"#"}
                    size={"large"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__rSfE0)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hIGf
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Our Recommendation"
                      : "Our Recommendation"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lqGQs)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__q1IPl)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={
                        hasVariant(globalVariants, "screen", "mobile")
                          ? "115px"
                          : "144.97px"
                      }
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/bestSellerSvg.svg",
                        fullWidth: 147,
                        fullHeight: 150,
                        aspectRatio: 0.97973
                      }}
                    />

                    <h4
                      className={classNames(
                        projectcss.all,
                        projectcss.h4,
                        projectcss.__wab_text,
                        sty.h4__vsYz
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobile")
                        ? "Pro"
                        : "Pro"}
                    </h4>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__q7Smm
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
                      }
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jk5C)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"238px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/lineSvg.svg",
                        fullWidth: 300,
                        fullHeight: 3,
                        aspectRatio: 119
                      }}
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__fh2Sl)}
                    >
                      <h3
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.h3__ybe91
                        )}
                      >
                        {"$50"}
                      </h3>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eZswn
                        )}
                      >
                        {"/ Month"}
                      </div>
                    </div>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__psL8T)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"238px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/lineSvg.svg",
                        fullWidth: 300,
                        fullHeight: 3,
                        aspectRatio: 119
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yud9A
                      )}
                    >
                      {"Feature"}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xiOk3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vMcg7
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bCrMk
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__rdDUg)}
                            displayHeight={"20px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"20px"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/light_saa_s_landing_page/images/tickCircleBlueSvg.svg",
                              fullWidth: 150,
                              fullHeight: 150,
                              aspectRatio: 1
                            }}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__bCdLv
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ulmNe
                            )}
                          >
                            {"Unlimited issue"}
                          </div>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___5KSkA
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__nslNq
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img__fwQ8Z)}
                            displayHeight={"20px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"20px"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/light_saa_s_landing_page/images/tickCircleBlueSvg.svg",
                              fullWidth: 150,
                              fullHeight: 150,
                              aspectRatio: 1
                            }}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__totVy
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__iPc5
                            )}
                          >
                            {"Free domains & hosting"}
                          </div>
                        </div>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ky24I
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__uf4EO
                          )}
                        >
                          <PlasmicImg__
                            alt={""}
                            className={classNames(sty.img___1EwC)}
                            displayHeight={"20px"}
                            displayMaxHeight={"none"}
                            displayMaxWidth={"100%"}
                            displayMinHeight={"0"}
                            displayMinWidth={"0"}
                            displayWidth={"20px"}
                            loading={"lazy"}
                            src={{
                              src: "/plasmic/light_saa_s_landing_page/images/tickCircleBlueSvg.svg",
                              fullWidth: 150,
                              fullHeight: 150,
                              aspectRatio: 1
                            }}
                          />
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__izyHx
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lGeqt
                            )}
                          >
                            {"10 team accounts"}
                          </div>
                        </div>
                      </div>
                    </div>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__lEhss
                      )}
                      label={
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___7SoJj
                          )}
                        >
                          {"Get Started"}
                        </div>
                      }
                      linkTo={"#"}
                      size={"large"}
                    />
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__aBiXd)}>
                  <h4
                    className={classNames(
                      projectcss.all,
                      projectcss.h4,
                      projectcss.__wab_text,
                      sty.h4__hEbp
                    )}
                  >
                    {"Enterprise"}
                  </h4>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xOPy
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobile")
                      ? "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
                      : "Lorem ipsum dolor sit amet, consectetur adipiscing elit"}
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__pregy)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"238px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/lineSvg.svg",
                      fullWidth: 300,
                      fullHeight: 3,
                      aspectRatio: 119
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox__ie1Z6)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__vjLh
                      )}
                    >
                      {"$300"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___76MJ4
                      )}
                    >
                      {"/ Month"}
                    </div>
                  </div>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___9Dmod)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"238px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/light_saa_s_landing_page/images/lineSvg.svg",
                      fullWidth: 300,
                      fullHeight: 3,
                      aspectRatio: 119
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sXxf1
                    )}
                  >
                    {"Feature"}
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__qqcaX)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bTnAj)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__pdJtf
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__hIV9)}
                          displayHeight={"20px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"20px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBlueSvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__rwdD
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zFwAo
                          )}
                        >
                          {"Unlimited issue"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__j6NVd)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___4Nsg5
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__gopzs)}
                          displayHeight={"20px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"20px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBlueSvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__g3VK
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___9ZwtM
                          )}
                        >
                          {"Free domains & hosting"}
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bDf4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__n06ZT
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__ofIaf)}
                          displayHeight={"20px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"20px"}
                          loading={"lazy"}
                          src={{
                            src: "/plasmic/light_saa_s_landing_page/images/tickCircleBlueSvg.svg",
                            fullWidth: 150,
                            fullHeight: 150,
                            aspectRatio: 1
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___8Andk
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___2Dfij
                          )}
                        >
                          {"Unlimited team accounts"}
                        </div>
                      </div>
                    </div>
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__iuTvu)}
                    label={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zfyt6
                        )}
                      >
                        {"Get Started"}
                      </div>
                    }
                    linkTo={"#"}
                    size={"large"}
                  />
                </div>
              </Stack__>
            </div>
          </Section>
          <Section
            className={classNames("__wab_instance", sty.section__knjWv)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : "faq"
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__wxBLc)}>
              <div className={classNames(projectcss.all, sty.freeBox__ciVu1)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__bGgTg
                  )}
                >
                  {"Lorem Ipsum"}
                </div>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___2Zq1O
                  )}
                >
                  {"Lorem Ipsum"}
                </h2>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__h8GJ
                  )}
                >
                  {
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__vy1V8)}>
                <div className={classNames(projectcss.all, sty.freeBox__ztSaC)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___31Lny)}
                  >
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6___9Rct4
                      )}
                    >
                      {"Lorem ipsum dolor sit amet, consectetur"}
                    </h6>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___2Jf3R)}
                      displayHeight={"auto"}
                      displayMaxHeight={"24px"}
                      displayMaxWidth={"24px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/minusCirlceSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zG6Oi
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
                    }
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__eo1DX)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jrv7L)}
                  >
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__yEg3G
                      )}
                    >
                      {"Lorem ipsum dolor sit amet, consectetur"}
                    </h6>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__o34T3)}
                      displayHeight={"auto"}
                      displayMaxHeight={"24px"}
                      displayMaxWidth={"24px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/addCircleSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__dheZ5)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___5On6U)}
                  >
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6___5Epmp
                      )}
                    >
                      {"Lorem ipsum dolor sit amet, consectetur"}
                    </h6>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__zzZ6Z)}
                      displayHeight={"auto"}
                      displayMaxHeight={"24px"}
                      displayMaxWidth={"24px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/addCircleSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___3Wttl)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__f4B0W)}
                  >
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__z2VHm
                      )}
                    >
                      {"Lorem ipsum dolor sit amet, consectetur"}
                    </h6>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___1Uqz0)}
                      displayHeight={"auto"}
                      displayMaxHeight={"24px"}
                      displayMaxWidth={"24px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/addCircleSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.freeBox__xhzR9)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mepGt)}
                  >
                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6___1G8ZB
                      )}
                    >
                      {"Lorem ipsum dolor sit amet, consectetur"}
                    </h6>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qQqnW)}
                      displayHeight={"auto"}
                      displayMaxHeight={"24px"}
                      displayMaxWidth={"24px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/light_saa_s_landing_page/images/addCircleSvg.svg",
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </Section>
          <Section
            background={"blue"}
            className={classNames("__wab_instance", sty.section__wUkHb)}
            size={
              hasVariant(globalVariants, "screen", "mobile")
                ? "fullContentWidth"
                : "fullContentWidth"
            }
          >
            <div className={classNames(projectcss.all, sty.freeBox__nmEav)}>
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__sf2VH
                )}
              >
                {"Lorem Ipsum"}
              </h1>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___9Tw3E
                )}
              >
                {
                  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex."
                }
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__spNCs)}
              >
                <TextInput
                  data-plasmic-name={"textInput"}
                  data-plasmic-override={overrides.textInput}
                  className={classNames("__wab_instance", sty.textInput)}
                  onChange={async (...eventArgs: any) => {
                    ((...eventArgs) => {
                      generateStateOnChangeProp($state, ["textInput", "value"])(
                        (e => e.target?.value).apply(null, eventArgs)
                      );
                    }).apply(null, eventArgs);

                    if (
                      eventArgs.length > 1 &&
                      eventArgs[1] &&
                      eventArgs[1]._plasmic_state_init_
                    ) {
                      return;
                    }
                  }}
                  value={
                    generateStateValueProp($state, ["textInput", "value"]) ?? ""
                  }
                />

                <Button
                  className={classNames("__wab_instance", sty.button__utCgy)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uaW10
                      )}
                    >
                      {"Subscribe"}
                    </div>
                  }
                  linkTo={"#"}
                  size={"large"}
                />
              </Stack__>
            </div>
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__cEXwb)}
              displayHeight={"auto"}
              displayMaxHeight={"700px"}
              displayMaxWidth={"1140px"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
              src={{
                src: "/plasmic/light_saa_s_landing_page/images/image6Png.png",
                fullWidth: 2880,
                fullHeight: 900,
                aspectRatio: undefined
              }}
            />
          </Section>
          <FooterSection
            data-plasmic-name={"footerSection"}
            data-plasmic-override={overrides.footerSection}
            className={classNames("__wab_instance", sty.footerSection)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headerHeroSection",
    "navbar",
    "svg",
    "textInput",
    "footerSection"
  ],
  headerHeroSection: ["headerHeroSection", "navbar", "svg"],
  navbar: ["navbar"],
  svg: ["svg"],
  textInput: ["textInput"],
  footerSection: ["footerSection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headerHeroSection: "div";
  navbar: typeof Navbar;
  svg: "svg";
  textInput: typeof TextInput;
  footerSection: typeof FooterSection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage2__VariantsArgs;
    args?: PlasmicHomepage2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage2__ArgProps,
          internalVariantPropNames: PlasmicHomepage2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage2";
  } else {
    func.displayName = `PlasmicHomepage2.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage2 = Object.assign(
  // Top-level PlasmicHomepage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headerHeroSection: makeNodeComponent("headerHeroSection"),
    navbar: makeNodeComponent("navbar"),
    svg: makeNodeComponent("svg"),
    textInput: makeNodeComponent("textInput"),
    footerSection: makeNodeComponent("footerSection"),

    // Metadata about props expected for PlasmicHomepage2
    internalVariantProps: PlasmicHomepage2__VariantProps,
    internalArgProps: PlasmicHomepage2__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Home",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage2;
/* prettier-ignore-end */
